/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hfeng' at '16-9-10 下午4:06' with Gradle 3.0
 *
 * @author hfeng, @date 16-9-10 下午4:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
